# LAB | Extractive Question Answering

This notebook demonstrates how Pinecone helps you build an extractive question-answering application. To build an extractive question-answering system, we need three main components:

- A vector index to store and run semantic search
- A retriever model for embedding context passages
- A reader model to extract answers

We will use the SQuAD dataset, which consists of **questions** and **context** paragraphs containing question **answers**. We generate embeddings for the context passages using the retriever, index them in the vector database, and query with semantic search to retrieve the top k most relevant contexts containing potential answers to our question. We then use the reader model to extract the answers from the returned contexts.

Let's get started by installing the packages needed for notebook to run:

In [6]:
from google.colab import userdata
import os

# Retrieve the API keys
OPENAI_API_KEY = userdata.get('OPENAI_API_KEY')
PINECONE_API_KEY = userdata.get('PINECONE_API_KEY')

# Set as environment variables
os.environ['OPENAI_API_KEY'] = OPENAI_API_KEY
os.environ['PINECONE_API_KEY'] = PINECONE_API_KEY

print("OpenAI API key loaded and set as environment variable.")
print("Pinecone API key loaded and set as environment variable.")

OpenAI API key loaded and set as environment variable.
Pinecone API key loaded and set as environment variable.

# Install Dependencies

In [8]:
!pip install -qU datasets pinecone-client sentence-transformers torch

# Load Dataset

Now let's load the SQUAD dataset from the HuggingFace Model Hub. We load the dataset into a pandas dataframe and filter the title, question, and context columns, and we drop any duplicate context passages.

In [10]:
from datasets import load_dataset

# load the squad dataset into a pandas dataframe
df = load_dataset("squad", split="train").to_pandas()

In [11]:
df.head()

,id,title,context,question,answers
0,5733be284776f41900661182,University_of_Notre_Dame,"Architecturally, the school has a Catholic cha...",To whom did the Virgin Mary allegedly appear i...,"{'text': ['Saint Bernadette Soubirous'], 'answ..."
1,5733be284776f4190066117f,University_of_Notre_Dame,"Architecturally, the school has a Catholic cha...",What is in front of the Notre Dame Main Building?,"{'text': ['a copper statue of Christ'], 'answe..."
2,5733be284776f41900661180,University_of_Notre_Dame,"Architecturally, the school has a Catholic cha...",The Basilica of the Sacred heart at Notre Dame...,"{'text': ['the Main Building'], 'answer_start'..."
3,5733be284776f41900661181,University_of_Notre_Dame,"Architecturally, the school has a Catholic cha...",What is the Grotto at Notre Dame?,{'text': ['a Marian place of prayer and reflec...
4,5733be284776f4190066117e,University_of_Notre_Dame,"Architecturally, the school has a Catholic cha...",What sits on top of the Main Building at Notre...,{'text': ['a golden statue of the Virgin Mary'...

In [12]:
# select only title and context column
df = df[["title", "context"]]
df = df.drop_duplicates(subset='context')
df

,title,context
0,University_of_Notre_Dame,"Architecturally, the school has a Catholic cha..."
5,University_of_Notre_Dame,"As at most other universities, Notre Dame's st..."
10,University_of_Notre_Dame,The university is the major seat of the Congre...
15,University_of_Notre_Dame,The College of Engineering was established in ...
20,University_of_Notre_Dame,All of Notre Dame's undergraduate students are...
...,...,...
87574,Kathmandu,"Institute of Medicine, the central college of ..."
87579,Kathmandu,Football and Cricket are the most popular spor...
87584,Kathmandu,The total length of roads in Nepal is recorded...
87589,Kathmandu,The main international airport serving Kathman...
87594,Kathmandu,"Kathmandu Metropolitan City (KMC), in order to..."

# Initialize Pinecone Index

The Pinecone index stores vector representations of our context passages which we can retrieve using another vector (query vector). We first need to initialize our connection to Pinecone to create our vector index. For this, we need a free [API key]("https://app.pinecone.io/"), and then we initialize the connection like so:

In [12]:
!pip install -qU langchain-pinecone pinecone-notebooks

In [13]:
from pinecone import Pinecone, ServerlessSpec

spec = ServerlessSpec(
    cloud="aws", region="us-east-1"
)

# connect to pinecone environment
pc = Pinecone(
    api_key = PINECONE_API_KEY,
    environment='us-east-1'  # find next to API key in console
)

In [55]:
!pip uninstall -y pinecone-client pinecone

Found existing installation: pinecone-client 6.0.0
Uninstalling pinecone-client-6.0.0:
  Successfully uninstalled pinecone-client-6.0.0
Found existing installation: pinecone 7.3.0
Uninstalling pinecone-7.3.0:
  Successfully uninstalled pinecone-7.3.0

Now we create a new index called "question-answering" — we can name the index anything we want. We specify the metric type as "cosine" and dimension as 384 because the retriever we use to generate context embeddings is optimized for cosine similarity and outputs 384-dimension vectors.

In [7]:
!pip install pinecone

Collecting pinecone
  Downloading pinecone-8.0.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: certifi>=2019.11.17 in /usr/local/lib/python3.12/dist-packages (from pinecone) (2025.10.5)
Requirement already satisfied: orjson>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from pinecone) (3.11.4)
Collecting pinecone-plugin-assistant<4.0.0,>=3.0.1 (from pinecone)
  Downloading pinecone_plugin_assistant-3.0.1-py3-none-any.whl.metadata (30 kB)
Collecting pinecone-plugin-interface<0.1.0,>=0.0.7 (from pinecone)
  Downloading pinecone_plugin_interface-0.0.7-py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: python-dateutil>=2.5.3 in /usr/local/lib/python3.12/dist-packages (from pinecone) (2.9.0.post0)
Requirement already satisfied: typing-extensions>=3.7.4 in /usr/local/lib/python3.12/dist-packages (from pinecone) (4.15.0)
Requirement already satisfied: urllib3>=1.26.5 in /usr/local/lib/python3.12/dist-packages (from pinecone) (2.5.0)
Collecting packaging<25.0,>=24.2 (from pinecone-plugin-assistant<4.0.0,>=3.0.1->pinecone)
  Downloading packaging-24.2-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: requests<3.0.0,>=2.32.3 in /usr/local/lib/python3.12/dist-packages (from pinecone-plugin-assistant<4.0.0,>=3.0.1->pinecone) (2.32.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.5.3->pinecone) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.3->pinecone-plugin-assistant<4.0.0,>=3.0.1->pinecone) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.3->pinecone-plugin-assistant<4.0.0,>=3.0.1->pinecone) (3.11)
Downloading pinecone-8.0.0-py3-none-any.whl (745 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 745.9/745.9 kB 19.6 MB/s eta 0:00:00
Downloading pinecone_plugin_assistant-3.0.1-py3-none-any.whl (280 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 280.9/280.9 kB 25.3 MB/s eta 0:00:00
Downloading pinecone_plugin_interface-0.0.7-py3-none-any.whl (6.2 kB)
Downloading packaging-24.2-py3-none-any.whl (65 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.5/65.5 kB 4.6 MB/s eta 0:00:00
Installing collected packages: pinecone-plugin-interface, packaging, pinecone-plugin-assistant, pinecone
  Attempting uninstall: packaging
    Found existing installation: packaging 25.0
    Uninstalling packaging-25.0:
      Successfully uninstalled packaging-25.0
Successfully installed packaging-24.2 pinecone-8.0.0 pinecone-plugin-assistant-3.0.1 pinecone-plugin-interface-0.0.7

In [7]:
from pinecone import Pinecone, ServerlessSpec

pc = Pinecone(api_key=PINECONE_API_KEY)

index_name = "question-answering"

# check if the index exists
if index_name not in pc.list_indexes().names():
    pc.create_index(
        name=index_name,
        dimension=384,
        metric="cosine",
        spec=ServerlessSpec(
            cloud="aws", region="us-east-1"
        )
    )

# Initialize Retriever

Next, we need to initialize our retriever. The retriever will mainly do two things:

- Generate embeddings for all context passages (context vectors/embeddings)
- Generate embeddings for our questions (query vector/embedding)

The retriever will generate embeddings in a way that the questions and context passages containing answers to our questions are nearby in the vector space. We can use cosine similarity to calculate the similarity between the query and context embeddings to find the context passages that contain potential answers to our question.

We will use a SentenceTransformer model named ``multi-qa-MiniLM-L6-cos-v1`` designed for semantic search and trained on 215M (question, answer) pairs from diverse sources as our retriever.

In [1]:
!pip install -U sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.1.2)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.57.1)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.8.0+cu126)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (0.36.0)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (11.3.0)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2.32.4)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.2.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2024.11.6)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.6.2)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2025.10.5)

In [2]:
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Using device:", device)

Using device: cuda

In [3]:
from sentence_transformers import SentenceTransformer

retriever = SentenceTransformer("all-MiniLM-L6-v2", device=device)
print("Retriever loaded successfully on", device)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Retriever loaded successfully on cuda

# Generate Embeddings and Upsert
""import torch
from sentence_transformers import SentenceTransformer

# set device to GPU if available
device = 'cuda' if torch.cuda.is_available() else 'cpu'
# load the retriever model from huggingface model hub
retriever = None #use the 'multi-qa-MiniLM-L6-cos-v1' model from HuggingFace to build the retriever
retriever""

Next, we need to generate embeddings for the context passages. We will do this in batches to help us more quickly generate embeddings and upload them to the Pinecone index. When passing the documents to Pinecone, we need an id (a unique value), context embedding, and metadata for each document representing context passages in the dataset. The metadata is a dictionary containing data relevant to our embeddings, such as the article title, context passage, etc.

In [8]:
index = pc.Index(index_name)

In [13]:
from tqdm.auto import tqdm

# we will use batches of 64
batch_size = 64

for i in tqdm(range(0, len(df), batch_size)):
    # find end of batch
    end = min(i + batch_size, len(df))

    # extract batch
    batch = df.iloc[i:end]
    # generate embeddings for batch
    emb = retriever.encode(
        batch["context"].tolist(),
        show_progress_bar=False
    ).tolist()
    # get metadata
    meta = batch[["title", "context"]].to_dict(orient="records")
    # create unique IDs
    ids = [str(idx) for idx in batch.index]
    # add all to upsert list
    to_upsert = [
        {
            "id": _id,
            "values": vector,
            "metadata": m,
        }
        for _id, vector, m in zip(ids, emb, meta)
    ]
    # upsert/insert these records to pinecone
    _ = index.upsert(vectors=to_upsert)

# check that we have all vectors in index
index.describe_index_stats()

  0%|          | 0/296 [00:00<?, ?it/s]

{'_response_info': {'raw_headers': {'connection': 'keep-alive',
                                    'content-length': '189',
                                    'content-type': 'application/json',
                                    'date': 'Thu, 20 Nov 2025 16:35:20 GMT',
                                    'grpc-status': '0',
                                    'server': 'envoy',
                                    'x-envoy-upstream-service-time': '32',
                                    'x-pinecone-request-id': '6455903296080860261',
                                    'x-pinecone-request-latency-ms': '31'}},
 'dimension': 384,
 'index_fullness': 0.0,
 'memoryFullness': 0.0,
 'metric': 'cosine',
 'namespaces': {'__default__': {'vector_count': 18891}},
 'storageFullness': 0.0,
 'total_vector_count': 18891,
 'vector_type': 'dense'}

# Initialize Reader

We use the `deepset/electra-base-squad2` model from the HuggingFace model hub as our reader model. We load this model into a "question-answering" pipeline from HuggingFace transformers and feed it our questions and context passages individually. The model gives a prediction for each context we pass through the pipeline.

In [14]:
from transformers import pipeline

model_name = 'deepset/electra-base-squad2'
# load the reader model into a question-answering pipeline
reader = pipeline(tokenizer=model_name, model=model_name, task='question-answering', device=device)
reader

config.json:   0%|          | 0.00/635 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/436M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/200 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

Device set to use cuda

Now all the components we need are ready. Let's write some helper functions to execute our queries. The `get_context` function retrieves the context embeddings containing answers to our question from the Pinecone index, and the `extract_answer` function extracts the answers from these context passages.

In [15]:
# gets context passages from the pinecone index
def get_context(question, top_k=5):
    # 1. generate embeddings for the question (single vector)
    xq = retriever.encode([question], show_progress_bar=False).tolist()[0]

    # 2. search pinecone index for context passages with the answer
    xc = index.query(
        vector=xq,
        top_k=top_k,
        include_metadata=True
    )

    # 3. extract the context passages from pinecone search result
    #    (here we return a list of context strings)
    c = [m["metadata"]["context"] for m in xc["matches"]]

    return c

In [16]:
from pprint import pprint

def extract_answer(question, context_list):
    results = []

    for c in context_list:
        # run the reader model
        answer = reader(question=question, context=c)

        # include context for later reference
        answer["context"] = c

        results.append(answer)

    # sort by confidence score
    sorted_results = sorted(results, key=lambda x: x['score'], reverse=True)

    # pretty print
    pprint(sorted_results)

    return sorted_results

In [17]:
question = "How much oil is Egypt producing in a day?"
context = get_context(question, top_k = 1)
context

['Egypt was producing 691,000 bbl/d of oil and 2,141.05 Tcf of natural gas (in 2013), which makes Egypt as the largest oil producer not member of the Organization of the Petroleum Exporting Countries (OPEC) and the second-largest dry natural gas producer in Africa. In 2013, Egypt was the largest consumer of oil and natural gas in Africa, as more than 20% of total oil consumption and more than 40% of total dry natural gas consumption in Africa. Also, Egypt possesses the largest oil refinery capacity in Africa 726,000 bbl/d (in 2012). Egypt is currently planning to build its first nuclear power plant in El Dabaa city, northern Egypt.']

As we can see, the retiever is working fine and gets us the context passage that contains the answer to our question. Now let's use the reader to extract the exact answer from the context passage.

In [18]:
extract_answer(question, context)

[{'answer': '691,000 bbl/d',
  'context': 'Egypt was producing 691,000 bbl/d of oil and 2,141.05 Tcf of '
             'natural gas (in 2013), which makes Egypt as the largest oil '
             'producer not member of the Organization of the Petroleum '
             'Exporting Countries (OPEC) and the second-largest dry natural '
             'gas producer in Africa. In 2013, Egypt was the largest consumer '
             'of oil and natural gas in Africa, as more than 20% of total oil '
             'consumption and more than 40% of total dry natural gas '
             'consumption in Africa. Also, Egypt possesses the largest oil '
             'refinery capacity in Africa 726,000 bbl/d (in 2012). Egypt is '
             'currently planning to build its first nuclear power plant in El '
             'Dabaa city, northern Egypt.',
  'end': 33,
  'score': 0.9999855201993455,
  'start': 20}]

[{'score': 0.9999855201993455,
  'start': 20,
  'end': 33,
  'answer': '691,000 bbl/d',
  'context': 'Egypt was producing 691,000 bbl/d of oil and 2,141.05 Tcf of natural gas (in 2013), which makes Egypt as the largest oil producer not member of the Organization of the Petroleum Exporting Countries (OPEC) and the second-largest dry natural gas producer in Africa. In 2013, Egypt was the largest consumer of oil and natural gas in Africa, as more than 20% of total oil consumption and more than 40% of total dry natural gas consumption in Africa. Also, Egypt possesses the largest oil refinery capacity in Africa 726,000 bbl/d (in 2012). Egypt is currently planning to build its first nuclear power plant in El Dabaa city, northern Egypt.'}]

The reader model predicted with 99% accuracy the correct answer *691,000 bbl/d* as seen from the context passage. Let's run few more queries.

In [19]:
question = "What are the first names of the men that invented youtube?"
context = get_context(question, top_k=1)
extract_answer(question, context)

[{'answer': 'Hurley and Chen',
  'context': 'According to a story that has often been repeated in the media, '
             'Hurley and Chen developed the idea for YouTube during the early '
             'months of 2005, after they had experienced difficulty sharing '
             "videos that had been shot at a dinner party at Chen's apartment "
             'in San Francisco. Karim did not attend the party and denied that '
             'it had occurred, but Chen commented that the idea that YouTube '
             'was founded after a dinner party "was probably very strengthened '
             'by marketing ideas around creating a story that was very '
             'digestible".',
  'end': 79,
  'score': 0.9999276399612427,
  'start': 64}]

[{'score': 0.9999276399612427,
  'start': 64,
  'end': 79,
  'answer': 'Hurley and Chen',
  'context': 'According to a story that has often been repeated in the media, Hurley and Chen developed the idea for YouTube during the early months of 2005, after they had experienced difficulty sharing videos that had been shot at a dinner party at Chen\'s apartment in San Francisco. Karim did not attend the party and denied that it had occurred, but Chen commented that the idea that YouTube was founded after a dinner party "was probably very strengthened by marketing ideas around creating a story that was very digestible".'}]

In [20]:
question = "What is Albert Eistein famous for?"
context = get_context(question, top_k=1)
extract_answer(question, context)

[{'answer': 'Industrial Prince"',
  'context': 'In October 1919, Albert went up to Trinity College, Cambridge, '
             'where he studied history, economics and civics for a year. On 4 '
             'June 1920, he was created Duke of York, Earl of Inverness and '
             'Baron Killarney. He began to take on more royal duties. He '
             'represented his father, and toured coal mines, factories, and '
             'railyards. Through such visits he acquired the nickname of the '
             '"Industrial Prince". His stammer, and his embarrassment over it, '
             'together with his tendency to shyness, caused him to appear much '
             'less impressive than his older brother, Edward. However, he was '
             'physically active and enjoyed playing tennis. He played at '
             "Wimbledon in the Men's Doubles with Louis Greig in 1926, losing "
             'in the first round. He developed an interest in working '
             'conditions, and was President of the Industrial Welfare Society. '
             'His series of annual summer camps for boys between 1921 and 1939 '
             'brought together boys from different social backgrounds.',
  'end': 392,
  'score': 0.8287104964256287,
  'start': 374}]

[{'score': 0.8287104964256287,
  'start': 374,
  'end': 392,
  'answer': 'Industrial Prince"',
  'context': 'In October 1919, Albert went up to Trinity College, Cambridge, where he studied history, economics and civics for a year. On 4 June 1920, he was created Duke of York, Earl of Inverness and Baron Killarney. He began to take on more royal duties. He represented his father, and toured coal mines, factories, and railyards. Through such visits he acquired the nickname of the "Industrial Prince". His stammer, and his embarrassment over it, together with his tendency to shyness, caused him to appear much less impressive than his older brother, Edward. However, he was physically active and enjoyed playing tennis. He played at Wimbledon in the Men\'s Doubles with Louis Greig in 1926, losing in the first round. He developed an interest in working conditions, and was President of the Industrial Welfare Society. His series of annual summer camps for boys between 1921 and 1939 brought together boys from different social backgrounds.'}]

Let's run another question. This time for top 3 context passages from the retriever.

In [21]:
question = "Who was the first person to step foot on the moon?"
context = get_context(question, top_k=3)
extract_answer(question, context)

[{'answer': 'Armstrong',
  'context': 'The trip to the Moon took just over three days. After achieving '
             'orbit, Armstrong and Aldrin transferred into the Lunar Module, '
             'named Eagle, and after a landing gear inspection by Collins '
             'remaining in the Command/Service Module Columbia, began their '
             'descent. After overcoming several computer overload alarms '
             'caused by an antenna switch left in the wrong position, and a '
             'slight downrange error, Armstrong took over manual flight '
             'control at about 180 meters (590 ft), and guided the Lunar '
             'Module to a safe landing spot at 20:18:04 UTC, July 20, 1969 '
             '(3:17:04 pm CDT). The first humans on the Moon would wait '
             'another six hours before they ventured out of their craft. At '
             '02:56 UTC, July 21 (9:56 pm CDT July 20), Armstrong became the '
             'first human to set foot on the Moon.',
  'end': 80,
  'score': 0.9998037815093994,
  'start': 71},
 {'answer': 'Aldrin',
  'context': 'The first step was witnessed by at least one-fifth of the '
             'population of Earth, or about 723 million people. His first '
             "words when he stepped off the LM's landing footpad were, "
             '"That\'s one small step for [a] man, one giant leap for '
             'mankind." Aldrin joined him on the surface almost 20 minutes '
             'later. Altogether, they spent just under two and one-quarter '
             'hours outside their craft. The next day, they performed the '
             'first launch from another celestial body, and rendezvoused back '
             'with Columbia.',
  'end': 246,
  'score': 0.7011048772837967,
  'start': 240},
 {'answer': 'Frank Borman',
  'context': 'On December 21, 1968, Frank Borman, James Lovell, and William '
             'Anders became the first humans to ride the Saturn V rocket into '
             'space on Apollo 8. They also became the first to leave low-Earth '
             'orbit and go to another celestial body, and entered lunar orbit '
             'on December 24. They made ten orbits in twenty hours, and '
             'transmitted one of the most watched TV broadcasts in history, '
             'with their Christmas Eve program from lunar orbit, that '
             'concluded with a reading from the biblical Book of Genesis. Two '
             'and a half hours after the broadcast, they fired their engine to '
             'perform the first trans-Earth injection to leave lunar orbit and '
             'return to the Earth. Apollo 8 safely landed in the Pacific ocean '
             "on December 27, in NASA's first dawn splashdown and recovery.",
  'end': 34,
  'score': 0.5020967973396182,
  'start': 22}]

[{'score': 0.9998037815093994,
  'start': 71,
  'end': 80,
  'answer': 'Armstrong',
  'context': 'The trip to the Moon took just over three days. After achieving orbit, Armstrong and Aldrin transferred into the Lunar Module, named Eagle, and after a landing gear inspection by Collins remaining in the Command/Service Module Columbia, began their descent. After overcoming several computer overload alarms caused by an antenna switch left in the wrong position, and a slight downrange error, Armstrong took over manual flight control at about 180 meters (590 ft), and guided the Lunar Module to a safe landing spot at 20:18:04 UTC, July 20, 1969 (3:17:04 pm CDT). The first humans on the Moon would wait another six hours before they ventured out of their craft. At 02:56 UTC, July 21 (9:56 pm CDT July 20), Armstrong became the first human to set foot on the Moon.'},
 {'score': 0.7011048772837967,
  'start': 240,
  'end': 246,
  'answer': 'Aldrin',
  'context': 'The first step was witnessed by at least one-fifth of the population of Earth, or about 723 million people. His first words when he stepped off the LM\'s landing footpad were, "That\'s one small step for [a] man, one giant leap for mankind." Aldrin joined him on the surface almost 20 minutes later. Altogether, they spent just under two and one-quarter hours outside their craft. The next day, they performed the first launch from another celestial body, and rendezvoused back with Columbia.'},
 {'score': 0.5020967973396182,
  'start': 22,
  'end': 34,
  'answer': 'Frank Borman',
  'context': "On December 21, 1968, Frank Borman, James Lovell, and William Anders became the first humans to ride the Saturn V rocket into space on Apollo 8. They also became the first to leave low-Earth orbit and go to another celestial body, and entered lunar orbit on December 24. They made ten orbits in twenty hours, and transmitted one of the most watched TV broadcasts in history, with their Christmas Eve program from lunar orbit, that concluded with a reading from the biblical Book of Genesis. Two and a half hours after the broadcast, they fired their engine to perform the first trans-Earth injection to leave lunar orbit and return to the Earth. Apollo 8 safely landed in the Pacific ocean on December 27, in NASA's first dawn splashdown and recovery."}]

The result looks pretty good.

In [41]:
pc.delete_index(index_name)

In [22]:
question = "Who invented google?"
context = get_context(question, top_k=2)
extract_answer(question, context)

[{'answer': 'Sir Tim Berners-Lee',
  'context': 'The first web browser was invented in 1990 by Sir Tim '
             'Berners-Lee. Berners-Lee is the director of the World Wide Web '
             "Consortium (W3C), which oversees the Web's continued "
             'development, and is also the founder of the World Wide Web '
             'Foundation. His browser was called WorldWideWeb and later '
             'renamed Nexus.',
  'end': 65,
  'score': 0.00015699792129453272,
  'start': 46},
 {'answer': 'Richard Braithwait',
  'context': 'The first known use of the word "computer" was in 1613 in a book '
             'called The Yong Mans Gleanings by English writer Richard '
             'Braithwait: "I haue read the truest computer of Times, and the '
             'best Arithmetician that euer breathed, and he reduceth thy dayes '
             'into a short number." It referred to a person who carried out '
             'calculations, or computations. The word continued with the same '
             'meaning until the middle of the 20th century. From the end of '
             'the 19th century the word began to take on its more familiar '
             'meaning, a machine that carries out computations.',
  'end': 132,
  'score': 1.1125522161523071e-12,
  'start': 114}]

[{'score': 0.00015699792129453272,
  'start': 46,
  'end': 65,
  'answer': 'Sir Tim Berners-Lee',
  'context': "The first web browser was invented in 1990 by Sir Tim Berners-Lee. Berners-Lee is the director of the World Wide Web Consortium (W3C), which oversees the Web's continued development, and is also the founder of the World Wide Web Foundation. His browser was called WorldWideWeb and later renamed Nexus."},
 {'score': 1.1125522161523071e-12,
  'start': 114,
  'end': 132,
  'answer': 'Richard Braithwait',
  'context': 'The first known use of the word "computer" was in 1613 in a book called The Yong Mans Gleanings by English writer Richard Braithwait: "I haue read the truest computer of Times, and the best Arithmetician that euer breathed, and he reduceth thy dayes into a short number." It referred to a person who carried out calculations, or computations. The word continued with the same meaning until the middle of the 20th century. From the end of the 19th century the word began to take on its more familiar meaning, a machine that carries out computations.'}]

In [23]:
question = "Who was the first person with a car?"
context = get_context(question, top_k=2)
extract_answer(question, context)

[{'answer': 'Frank J. Sprague',
  'context': 'Richmond emerged a decade after the smoldering rubble of the '
             'Civil War to resume its position as an economic powerhouse, with '
             'iron front buildings and massive brick factories. Canal traffic '
             'peaked in the 1860s and slowly gave way to railroads, allowing '
             'Richmond to become a major railroad crossroads, eventually '
             "including the site of the world's first triple railroad "
             'crossing. Tobacco warehousing and processing continued to play a '
             "role, boosted by the world's first cigarette-rolling machine, "
             'invented by James Albert Bonsack of Roanoke in 1880/81. '
             "Contributing to Richmond's resurgence was the first successful "
             'electrically powered trolley system in the United States, the '
             'Richmond Union Passenger Railway. Designed by electric power '
             'pioneer Frank J. Sprague, the trolley system opened its first '
             'line in 1888, and electric streetcar lines rapidly spread to '
             "other cities across the country. Sprague's system used an "
             'overhead wire and trolley pole to collect current, with electric '
             "motors on the car's trucks. In Richmond, the transition from "
             'streetcars to buses began in May 1947 and was completed on '
             'November 25, 1949.',
  'end': 761,
  'score': 1.0245468085035014e-09,
  'start': 745},
 {'answer': 'Schwarzenegger.',
  'context': 'Schwarzenegger was the first civilian to purchase a Humvee. He '
             "was so enamored by the vehicle that he lobbied the Humvee's "
             'manufacturer, AM General, to produce a street-legal, civilian '
             'version, which they did in 1992; the first two Hummers they sold '
             'were also purchased by Schwarzenegger.',
  'end': 288,
  'score': 5.831893440388924e-10,
  'start': 273}]

[{'score': 1.0245468085035014e-09,
  'start': 745,
  'end': 761,
  'answer': 'Frank J. Sprague',
  'context': "Richmond emerged a decade after the smoldering rubble of the Civil War to resume its position as an economic powerhouse, with iron front buildings and massive brick factories. Canal traffic peaked in the 1860s and slowly gave way to railroads, allowing Richmond to become a major railroad crossroads, eventually including the site of the world's first triple railroad crossing. Tobacco warehousing and processing continued to play a role, boosted by the world's first cigarette-rolling machine, invented by James Albert Bonsack of Roanoke in 1880/81. Contributing to Richmond's resurgence was the first successful electrically powered trolley system in the United States, the Richmond Union Passenger Railway. Designed by electric power pioneer Frank J. Sprague, the trolley system opened its first line in 1888, and electric streetcar lines rapidly spread to other cities across the country. Sprague's system used an overhead wire and trolley pole to collect current, with electric motors on the car's trucks. In Richmond, the transition from streetcars to buses began in May 1947 and was completed on November 25, 1949."},
 {'score': 5.831893440388924e-10,
  'start': 273,
  'end': 288,
  'answer': 'Schwarzenegger.',
  'context': "Schwarzenegger was the first civilian to purchase a Humvee. He was so enamored by the vehicle that he lobbied the Humvee's manufacturer, AM General, to produce a street-legal, civilian version, which they did in 1992; the first two Hummers they sold were also purchased by Schwarzenegger."}]

In [24]:
question = "Who was responsible for world war?"
context = get_context(question, top_k=4)
extract_answer(question, context)

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

[{'answer': 'Nazi Germany',
  'context': 'Before the attack on Pearl Harbor, the 800,000-member America '
             'First Committee vehemently opposed any American intervention in '
             'the European conflict, even as America sold military aid to '
             'Britain and the Soviet Union through the Lend-Lease program. '
             'Opposition to war in the U.S. vanished after the attack. On 8 '
             'December, the United States, the United Kingdom, Canada, and the '
             'Netherlands declared war on Japan, followed by China and '
             'Australia the next day. Four days after Pearl Harbor, Nazi '
             'Germany and Fascist Italy declared war on the United States, '
             'drawing the country into a two-theater war. This is widely '
             'agreed to be a grand strategic blunder, as it abrogated the '
             "benefit Germany gained by Japan's distraction of the U.S. "
             '(predicted months before in a memo by Commander Arthur '
             'McCollum)[nb 12] and the reduction in aid to Britain, which both '
             'Congress and Hitler had managed to avoid during over a year of '
             'mutual provocation, which would otherwise have resulted.',
  'end': 497,
  'score': 0.485858678817749,
  'start': 485},
 {'answer': 'the Central Powers, led by the German Empire',
  'context': 'The First World War began in 1914 and lasted to the final '
             'Armistice in 1918. The Allied Powers, led by the British Empire, '
             'France, Russia until March 1918, Japan and the United States '
             'after 1917, defeated the Central Powers, led by the German '
             'Empire, Austro-Hungarian Empire and the Ottoman Empire. The war '
             'caused the disintegration of four empires—the Austro-Hungarian, '
             'German, Ottoman, and Russian ones—as well as radical change in '
             'the European and West Asian maps. The Allied powers before 1917 '
             'are referred to as the Triple Entente, and the Central Powers '
             'are referred to as the Triple Alliance.',
  'end': 249,
  'score': 0.006335493642836809,
  'start': 205},
 {'answer': 'many factors',
  'context': 'The causes of World War I included many factors, including the '
             'conflicts and antagonisms of the four decades leading up to the '
             'war. The Triple Entente was the name given to the loose '
             'alignment between the United Kingdom, France, and Russia after '
             'the signing of the Anglo-Russian Entente in 1907. The alignment '
             'of the three powers, supplemented by various agreements with '
             'Japan, the United States, and Spain, constituted a powerful '
             'counterweight to the Triple Alliance of Germany, '
             'Austria-Hungary, and Italy, the third having concluded an '
             'additional secret agreement with France effectively nullifying '
             'her Alliance commitments. Militarism, alliances, imperialism, '
             'and nationalism played major roles in the conflict. The '
             'immediate origins of the war lay in the decisions taken by '
             'statesmen and generals during the July Crisis of 1914, the spark '
             '(or casus belli) for which was the assassination of Archduke '
             'Franz Ferdinand of Austria.',
  'end': 47,
  'score': 0.004995308816432953,
  'start': 35},
 {'answer': 'the Central Powers',
  'context': 'The outbreak of World War I in 1914 was precipitated by the rise '
             'of nationalism in Southeastern Europe as the Great Powers took '
             'up sides. The Allies defeated the Central Powers in 1918. During '
             'the Paris Peace Conference the Big Four imposed their terms in a '
             'series of treaties, especially the Treaty of Versailles.',
  'end': 176,
  'score': 0.00023877984494902194,
  'start': 158}]

[{'score': 0.485858678817749,
  'start': 485,
  'end': 497,
  'answer': 'Nazi Germany',
  'context': "Before the attack on Pearl Harbor, the 800,000-member America First Committee vehemently opposed any American intervention in the European conflict, even as America sold military aid to Britain and the Soviet Union through the Lend-Lease program. Opposition to war in the U.S. vanished after the attack. On 8 December, the United States, the United Kingdom, Canada, and the Netherlands declared war on Japan, followed by China and Australia the next day. Four days after Pearl Harbor, Nazi Germany and Fascist Italy declared war on the United States, drawing the country into a two-theater war. This is widely agreed to be a grand strategic blunder, as it abrogated the benefit Germany gained by Japan's distraction of the U.S. (predicted months before in a memo by Commander Arthur McCollum)[nb 12] and the reduction in aid to Britain, which both Congress and Hitler had managed to avoid during over a year of mutual provocation, which would otherwise have resulted."},
 {'score': 0.006335493642836809,
  'start': 205,
  'end': 249,
  'answer': 'the Central Powers, led by the German Empire',
  'context': 'The First World War began in 1914 and lasted to the final Armistice in 1918. The Allied Powers, led by the British Empire, France, Russia until March 1918, Japan and the United States after 1917, defeated the Central Powers, led by the German Empire, Austro-Hungarian Empire and the Ottoman Empire. The war caused the disintegration of four empires—the Austro-Hungarian, German, Ottoman, and Russian ones—as well as radical change in the European and West Asian maps. The Allied powers before 1917 are referred to as the Triple Entente, and the Central Powers are referred to as the Triple Alliance.'},
 {'score': 0.004995308816432953,
  'start': 35,
  'end': 47,
  'answer': 'many factors',
  'context': 'The causes of World War I included many factors, including the conflicts and antagonisms of the four decades leading up to the war. The Triple Entente was the name given to the loose alignment between the United Kingdom, France, and Russia after the signing of the Anglo-Russian Entente in 1907. The alignment of the three powers, supplemented by various agreements with Japan, the United States, and Spain, constituted a powerful counterweight to the Triple Alliance of Germany, Austria-Hungary, and Italy, the third having concluded an additional secret agreement with France effectively nullifying her Alliance commitments. Militarism, alliances, imperialism, and nationalism played major roles in the conflict. The immediate origins of the war lay in the decisions taken by statesmen and generals during the July Crisis of 1914, the spark (or casus belli) for which was the assassination of Archduke Franz Ferdinand of Austria.'},
 {'score': 0.00023877984494902194,
  'start': 158,
  'end': 176,
  'answer': 'the Central Powers',
  'context': 'The outbreak of World War I in 1914 was precipitated by the rise of nationalism in Southeastern Europe as the Great Powers took up sides. The Allies defeated the Central Powers in 1918. During the Paris Peace Conference the Big Four imposed their terms in a series of treaties, especially the Treaty of Versailles.'}]

In [26]:
question = "Why was trump selected?"
context = get_context(question, top_k=1)
extract_answer(question, context)

[{'answer': 'Conservative Party',
  'context': 'On March 10, 2004, Bush officially clinched the number of '
             'delegates needed to be nominated at the 2004 Republican National '
             'Convention in New York City. Bush accepted the nomination on '
             'September 2, 2004, and selected Vice President Dick Cheney as '
             'his running mate. (In New York, the ticket was also on the '
             'ballot as candidates of the Conservative Party of New York '
             'State.) During the convention and throughout the campaign, Bush '
             'focused on two themes: defending America against terrorism and '
             'building an ownership society. The ownership society included '
             'allowing people to invest some of their Social Security in the '
             'stock market, increasing home and stock ownership, and '
             'encouraging more people to buy their own health insurance.',
  'end': 351,
  'score': 8.338459700496514e-09,
  'start': 333}]

[{'score': 8.338459700496514e-09,
  'start': 333,
  'end': 351,
  'answer': 'Conservative Party',
  'context': 'On March 10, 2004, Bush officially clinched the number of delegates needed to be nominated at the 2004 Republican National Convention in New York City. Bush accepted the nomination on September 2, 2004, and selected Vice President Dick Cheney as his running mate. (In New York, the ticket was also on the ballot as candidates of the Conservative Party of New York State.) During the convention and throughout the campaign, Bush focused on two themes: defending America against terrorism and building an ownership society. The ownership society included allowing people to invest some of their Social Security in the stock market, increasing home and stock ownership, and encouraging more people to buy their own health insurance.'}]

In [28]:
question = "Why is adidas doing badly?"
context = get_context(question, top_k=1)
extract_answer(question, context)

[{'answer': 'West',
  'context': 'On December 3, 2013, Adidas officially confirmed a new shoe '
             'collaboration deal with West. After months of anticipation and '
             'rumors, West confirmed the release of the Adidas Yeezy Boosts '
             'with a Twitter announcement directing fans to the domain '
             'yeezy.supply. In 2015, West unveiled his Yeezy Season clothing '
             'line, premiering Season 1 in collaboration with Adidas early in '
             'the year. The release of the Yeezy Boosts and the full Adidas '
             'collaboration was showcased in New York City on February 12, '
             '2015, with free streaming to 50 cinemas in 13 countries around '
             'the world. An initial release of the Adidas Yeezy Boosts was '
             'limited to 9000 pairs to be available only in New York City via '
             'the Adidas smartphone app; the Adidas Yeezy Boosts were sold out '
             'within 10 minutes. The shoes released worldwide on February 28, '
             '2015, were limited to select boutique stores and the Adidas UK '
             'stores. He followed with Season 2 later that year at New York '
             'Fashion Week. On February 11, West premiered his Yeezy Season 3 '
             'clothing line at Madison Square Garden in conjunction with the '
             'previewing of his album The Life of Pablo.',
  'end': 88,
  'score': 3.596710874010506e-13,
  'start': 84}]

[{'score': 3.596710874010506e-13,
  'start': 84,
  'end': 88,
  'answer': 'West',
  'context': 'On December 3, 2013, Adidas officially confirmed a new shoe collaboration deal with West. After months of anticipation and rumors, West confirmed the release of the Adidas Yeezy Boosts with a Twitter announcement directing fans to the domain yeezy.supply. In 2015, West unveiled his Yeezy Season clothing line, premiering Season 1 in collaboration with Adidas early in the year. The release of the Yeezy Boosts and the full Adidas collaboration was showcased in New York City on February 12, 2015, with free streaming to 50 cinemas in 13 countries around the world. An initial release of the Adidas Yeezy Boosts was limited to 9000 pairs to be available only in New York City via the Adidas smartphone app; the Adidas Yeezy Boosts were sold out within 10 minutes. The shoes released worldwide on February 28, 2015, were limited to select boutique stores and the Adidas UK stores. He followed with Season 2 later that year at New York Fashion Week. On February 11, West premiered his Yeezy Season 3 clothing line at Madison Square Garden in conjunction with the previewing of his album The Life of Pablo.'}]

### Add a few more questions. What did you observe?